---
title: Replication
---

```{r include=FALSE}

knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE,
                      message = FALSE)

```


```{r load_libraries}

library(tidyverse)

library(tidymodels)

library(readxl)

library(stargazer)

```


```{r setup}

theme_set(theme_bw() + theme(legend.position = "bottom",
                             legend.title = element_blank()))

```


```{r params}

params = list()

params$xreg_vars = c(
  "yield_curve_slope",
  "credit",
  "stock_prices",
  "debt_service_ratio",
  "real_consumption_per_capita",
  "investment",
  "current_account",
  "public_debt",
  "broad_money",
  "cpi"
)

params$vars_to_rates = c(
  "cpi",
  "real_consumption_per_capita",
  "stock_prices"
)

params$vars_to_diff = c(
  "credit",
  "broad_money",
  "public_debt",
  "debt_service_ratio",
  "investment",
  "current_account"
)

params$vars_to_gdp = c(
  "broad_money",
  "credit",
  "current_account")

```


```{r import_data}

raw_df = read_xlsx(paste0(
  file.path(Sys.getenv("USERPROFILE")),
  "\\OneDrive - Bank Of Israel\\Data\\",
  "MacroHistory\\JSTdatasetR3.xlsx"), sheet = "Data") %>% 
  arrange(country, year)

raw_df_python = read_csv("C:\\Users\\internet\\Desktop\\raw_df.csv",
                         col_types = cols(
  .default = col_double(),
  country = col_character(),
  iso = col_character()
)) %>% 
  suppressWarnings() %>% 
  select(-1)

if(all_equal(raw_df, raw_df_python)){print("raw df identical")}



all.equal(raw_df %>% 
            mutate(across(everything(), as.character)),
          raw_df_python %>% 
            mutate(across(everything(), as.character)))

```


```{r clean_df}

clean_df = raw_df %>% 
  mutate(across(-c("year","country"),
                ~replace(.,year %in% c(1914:1918,1934:1945), NA)))

clean_df_python = read_csv(paste0(file.path(Sys.getenv("USERPROFILE")),
                           "\\Desktop\\clean_df.csv"),
                           col_types = cols(
  .default = col_double(),
  country = col_character(),
  iso = col_character()
)) %>% 
  select(-1)

if(isTRUE(all.equal(clean_df %>% 
            mutate(across(everything(), as.character)),
          clean_df_python %>% 
           mutate(across(everything(), as.character))))){print("Clean df - passed")}

```



```{r transform_vars}

transformed_df = clean_df %>% 
  mutate(credit = tloans,
         stock_prices = stocks,
         real_consumption_per_capita = rconpc,
         investment = iy,
         current_account = ca,
         public_debt = debtgdp,
         broad_money = money) %>% 
  mutate(yield_curve_slope = ltrate - stir) %>% 
  mutate(debt_service_ratio = credit * ltrate / gdp) %>% 
  group_by(country) %>% 
  arrange(year) %>% 
  mutate(across(params$vars_to_gdp, ~ . / gdp)) %>% 
  mutate(across(params$vars_to_rates, ~ (. / lag(.,2)) - 1)) %>% 
  mutate(across(params$vars_to_diff, ~c(NA,NA, diff(.,2)))) %>% 
  mutate(across(c(params$vars_to_rates,
                  setdiff(params$vars_to_diff,"debt_service_ratio")),
                ~ . * 100)) %>% 
  ungroup() %>% 
  arrange(country, year)


transformed_df_python = read_csv(paste0(file.path(Sys.getenv("USERPROFILE")),
                           "\\Desktop\\transformed_df.csv"),
                           col_types = cols(
  .default = col_double(),
  country = col_character(),
  iso = col_character()
)) %>% 
  select(-1)



if(isTRUE(all.equal(
  transformed_df %>%
  select(names(transformed_df_python)) %>%
  # mutate(across(everything(), as.character)) %>% 
  identity(),
  transformed_df_python %>%
  # mutate(across(everything(), as.character)) %>% 
  identity()
  )
  )) {
  print("Transformed df - passed")
}



```


```{r add_global_vars}

global_df = transformed_df %>% 
  mutate(global_yield_curve_slope = map2_dbl(
    country, year,
    function(temp_country, temp_year){
      return(transformed_df %>% 
               filter(!country == temp_country) %>% 
               filter(year == temp_year) %>% 
               pull(yield_curve_slope) %>% 
               mean(.,na.rm = TRUE))
      })) %>% 
    mutate(global_credit_growth = map2_dbl(
    country, year,
    function(temp_country, temp_year){
      return(transformed_df %>% 
               filter(!country == temp_country) %>% 
               filter(year == temp_year) %>% 
               pull(credit) %>% 
               mean(., na.rm = TRUE))
      })) %>% 
  mutate(short_term_interest_rate = stir,
         long_term_interest_rate = ltrate,
         household_loans = thh / gdp,
         business_loans = tbus / gdp,
         house_prices = hpnom / lag(hpnom,2) - 1) %>% 
  group_by(country) %>% 
  mutate(across(c(household_loans,business_loans), ~c(NA,NA,diff(.,2)))) %>% 
  mutate(across(c(household_loans,business_loans,house_prices), ~ . * 100)) %>% 
  ungroup() %>% 
  mutate(household_loans = replace(household_loans, is.na(business_loans), NA))
  


global_df_python = read_csv(paste0(file.path(Sys.getenv("USERPROFILE")),
                           "\\Desktop\\global_df.csv"),
                           col_types = cols(
  .default = col_double(),
  country = col_character(),
  iso = col_character()
)) %>% 
  select(-1)


if(isTRUE(all.equal(global_df %>%
                    select(names(global_df_python)),
                    global_df_python)) &
   sum(is.na(global_df$global_credit_growth)) ==
   sum(is.na(global_df_python$global_credit_growth))
   ) {
  print("Global df - passed")
}


```


```{r add_crisis_vars}

crisis_df = global_df %>% 
  group_by(country) %>% 
  mutate(lead_crisis = if_else(
    lead(crisisJST) == 1 | lead(crisisJST,2) == 1,1,0)) %>% 
  # mutate(lead_crisis = factor(lead_crisis, levels = c(1,0))) %>% 
  mutate(lead_crisis = replace_na(lead_crisis,0)) %>%
  # filter(!year %in% c(sapply(year[crisisJST == 1],
  #                            function(temp){temp + 0:4}))) %>% 
  ungroup() %>% 
  filter(complete.cases(.)) %>% 
  identity()

crisis_df_python = read_csv(paste0(file.path(Sys.getenv("USERPROFILE")),
                           "\\Desktop\\crisis_df.csv"),
                           col_types = cols(
  .default = col_double(),
  country = col_character(),
  iso = col_character()
)) %>% 
  select(-1)


if(isTRUE(all.equal(crisis_df %>% 
                    rename(y = lead_crisis) %>% 
                    select(names(crisis_df_python)),
                    crisis_df_python))){
  print("Crisis df - passed")}

```


# EDA

The data set spans the period for `r paste0(range(df$year), collapse = "-")` for `r length(unique(df$iso))` countries. The countries are mainly European leaders as well as Japan and USA.


```{r cleaning_up_data}





```


```{r compare_crisis_vs_non_crisis, results="asis", eval=FALSE}

clean_df %>% 
  filter(crisisJST == 0) %>% 
  select(-c("crisisJST","iso")) %>% 
  mutate(lead_crisis = recode(lead_crisis,
                              `0` = "Normal",`1` = "Build_up")) %>% 
  pivot_longer(-c("year","lead_crisis")) %>% 
  group_by(lead_crisis, name) %>% 
  summarise(avg = mean(value)) %>% 
  pivot_wider(names_from = lead_crisis, values_from = avg) %>%
  as.data.frame() %>% 
  stargazer(type = "html",summary = FALSE, digits = 2,
            rownames = FALSE)
  

```










# Models

```{r models_spec}


models_df = list(logit = logistic_reg() %>% 
       set_engine("glm"),
     tree = decision_tree(mode = "classification") %>% 
       set_engine("C5.0")
     ) %>% 
  enframe(value = "model_spec")


```



```{r models_fit}

models_df = models_df %>% 
  mutate(models_wf = map(model_spec,function(temp_spec){
    
  temp_fit = workflow() %>% 
  add_formula(formula = formula("lead_crisis ~ .")) %>% 
  add_model(temp_spec) %>% 
  fit(data = clean_df)
    
  return(temp_fit)
    
  }))


```



```{r predictions}

models_df = models_df %>% 
  mutate(models_pred = map(models_wf,function(temp_wf){
    
  temp_pred = clean_df %>% 
  select(lead_crisis) %>% 
  bind_cols(predict(temp_wf, clean_df,type = "prob"))
    
  return(temp_pred)
    
  })) %>% 
  mutate(score = map(models_pred,function(temp_pred){
    
    temp_score = temp_pred %>% 
      roc_auc(truth = lead_crisis,.pred_1) %>% 
      pull(".estimate")
    
    return(temp_score)
    
  }))
    


```


